# General Jekyll Config
pygments: true
url: http://spitimage.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
markdown: kramdown

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: spitimage
    #bitbucket: philipj
    #hacker_news: swanson
    #stackexchange: 348619
    #stackoverflow: 348619
    twitter: spitimage
    #facebook: zuck
    #tumblr: animalygifs
    linkedin: aaronmnielsen
    #gplus: 110552447039675960964
    youtube: UCCFKcYHFZ1JW8w2ZFKAU5cg

  # "Hi, I'm _______"
  name: Aaron Nielsen
  email: spitimage@gmail.com
  tagline: "Collecting and connecting the dots."

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
